export interface Job {
  id: string; //generated by 
  question: string;
  source_url: string;
  status: 'submitted' | 'queued' | 'processing' | 'fetched' | 'done' | 'error';
  progress: number;
  result?: string;
  error?: string;
  created_at: Date;
  updated_at: Date;
}

export interface Transcript {
  id?: number; //auto generated on insertion
  video_id: string;
  url: string;
  transcript_text: string;  // Now: "start|text\nstart|text..." format
  language?: string;
  is_generated?: boolean;
  created_at?: Date;
  updated_at?: Date;
}